CREATE DATABASE IF NOT EXISTS `sso`;
CREATE DATABASE IF NOT EXISTS `fakultet`;
CREATE DATABASE IF NOT EXISTS `skola`;
CREATE DATABASE IF NOT EXISTS `szz`;
CREATE DATABASE IF NOT EXISTS `apr`;

CREATE USER IF NOT EXISTS 'root'@'localhost' IDENTIFIED BY 'local';
GRANT ALL ON *.* TO 'root'@'localhost';
