version: '3.3'

services:
  mysql:
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: local
    networks:
      - network
  sso-server:
    build:
      context: ../sso-server
      args:
        DOCKER_BUILDKIT: 1
    container_name: sso-server
    restart: always
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/sso?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=local
      - SERVER_PORT=9090
    depends_on:
      - mysql
    networks:
      - network
  fakultet-back:
    build:
      context: ../fakultet-back
      args:
        DOCKER_BUILDKIT: 1
    container_name: fakultet-back
    restart: always
    ports:
      - "8001:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/fakultet?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=local
      - SERVER_PORT=8080
    depends_on:
      - mysql
    networks:
      - network
  skola-back:
    build:
      context: ../skola-back
      args:
        DOCKER_BUILDKIT: 1
    container_name: skola-back
    restart: always
    ports:
      - "8002:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/skola?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=local
      - SERVER_PORT=8080
    depends_on:
      - mysql
    networks:
      - network
  szz-back:
    build:
      context: ../szz-back
      args:
        DOCKER_BUILDKIT: 1
    container_name: szz-back
    restart: always
    ports:
      - "8003:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/szz?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=local
      - SERVER_PORT=8080
    depends_on:
      - mysql
    networks:
      - network
  apr-back:
    build:
      context: ../apr-back
      args:
        DOCKER_BUILDKIT: 1
    container_name: apr-back
    restart: always
    ports:
      - "8004:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/apr?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=local
      - SERVER_PORT=8080
    depends_on:
      - mysql
    networks:
      - network
  fakultet-front:
    build:
      context: ../fakultet-front
      args:
        DOCKER_BUILDKIT: 1
    container_name: fakultet-front
    restart: always
    ports:
      - "4201:80"
    networks:
      - network
  skola-front:
    build:
      context: ../skola-front
      args:
        DOCKER_BUILDKIT: 1
    container_name: skola-front
    restart: always
    ports:
      - "4202:80"
    networks:
      - network
  szz-front:
    build:
      context: ../szz-front
      args:
        DOCKER_BUILDKIT: 1
    container_name: szz-front
    restart: always
    ports:
      - "4203:80"
    networks:
      - network
  apr-front:
    build:
      context: ../apr-front
      args:
        DOCKER_BUILDKIT: 1
    container_name: apr-front
    restart: always
    ports:
      - "4204:80"
    networks:
      - network

networks:
  network:
    driver: bridge